#!/Users/comatose/anaconda3/bin/python

import sys
import subprocess
import argparse
from tool import Extractor, Downloader

def open_file(file_path: str):
  try:
    if sys.platform.startswith("darwin"):  
      subprocess.run(["open", file_path])
    elif sys.platform.startswith("win32"):  
      subprocess.run(["start", "", file_path], shell=True)
    elif sys.platform.startswith("linux"):  
      subprocess.run(["xdg-open", file_path])
    else:
      print("Unsupported OS")
  except Exception as e:
    print(f"Error opening file: {e}")

def main():
  parser = argparse.ArgumentParser(
            description="Simple Youtube Thumbnail Downloader",
            epilog="Example usage:\n yt-thumb 'https://youtube.com/watch?v=x3fas9d8f7'",
            formatter_class=argparse.RawTextHelpFormatter
          )
  parser.add_argument("url", help="The Youtube Video's URL")
  parser.add_argument("--output", "-o", help="Output filename (default: <yt_ID>.jpg)")

  args = parser.parse_args()
  
  url = args.url
  e = Extractor(url)
  code = e.get_youtube_code()
  d_url = f"https://img.youtube.com/vi/{code}/maxresdefault.jpg"

  file_name = code if args.output is None else args.output

  d = Downloader(d_url, file_name)
  r = d.get(file_name)

  if '.jpg' in r:
    open_file(r)

if __name__ == '__main__':
  main()