#!/Users/comatose/anaconda3/bin/python

import sys
import subprocess
import argparse
from tool import Extractor, Downloader

def open_file(file_path: str):
  try:
    if sys.platform.startswith("darwin"):  
      subprocess.run(["open", file_path])
    elif sys.platform.startswith("win32"):  
      subprocess.run(["start", "", file_path], shell=True)
    elif sys.platform.startswith("linux"):  
      subprocess.run(["xdg-open", file_path])
    else:
      print("Unsupported OS")
  except Exception as e:
    print(f"Error opening file: {e}")

def main():
  parser = argparse.ArgumentParser(description="Simple Youtube Thumbnail Downloader")
  parser.add_argument("url", help="The Youtube Video's URL")

  args = parser.parse_args()
  
  url = args.url
  e = Extractor(url)
  code = e.get_youtube_code()
  d_url = f"https://img.youtube.com/vi/{code}/maxresdefault.jpg"

  d = Downloader(d_url, code)
  r = d.get()

  if '.jpg' in r:
    open_file(r)

if __name__ == '__main__':
  main()